#!/usr/bin/env dockerfile
# Dockerfile for TeX Live 2016 (historic tag)
#
# TL2016 is frozen; for MathML extraction our Lua pass needs `luamml` runtime
# (require("luamml-convert")). In older TLs this package may be missing from
# their tlnet-final; we vendor the runtime from the latest image into texmf-local.

FROM texlive/texlive:latest AS luamml_src

# Create an archive with luamml runtime without hard-coding the year of texlive:latest.
RUN set -e; \
    d="$(ls -d /usr/local/texlive/*/texmf-dist/tex/lualatex/luamml 2>/dev/null | head -1)"; \
    test -n "$d"; \
    tar -C "$d" -cf /luamml.tar .

FROM texlive/texlive:TL2016-historic
WORKDIR /workdir

RUN mkdir -p /usr/local/texlive/texmf-local/tex/lualatex/luamml && \
    mkdir -p /usr/local/texlive/texmf-local/tex/luatex/luamml
COPY --from=luamml_src /luamml.tar /tmp/luamml.tar
RUN set -e; \
    tar -C /usr/local/texlive/texmf-local/tex/lualatex/luamml -xf /tmp/luamml.tar; \
    # Make Lua modules discoverable by LuaTeX's require(): place them under tex/luatex too.
    find /usr/local/texlive/texmf-local/tex/lualatex/luamml -maxdepth 1 -type f -name '*.lua' -print0 | \
      xargs -0 -I{} cp -f {} /usr/local/texlive/texmf-local/tex/luatex/luamml/; \
    rm -f /tmp/luamml.tar; \
    mktexlsr

# Install LaTeXML (GitHub latest by default; override with --build-arg LATEXML_REF=<ref>).
ARG LATEXML_REPO=https://github.com/brucemiller/LaTeXML.git
ARG LATEXML_REF=
COPY install_latexml_github.sh /tmp/install_latexml_github.sh
RUN LATEXML_REPO="$LATEXML_REPO" LATEXML_REF="$LATEXML_REF" bash /tmp/install_latexml_github.sh && \
    rm -f /tmp/install_latexml_github.sh
