#!/usr/bin/env python3
"""
parse_lpsb_mcid.py - Parse LPSB MCID data from aux file

Parses the .aux file generated by lpsb-mcid.sty to extract:
1. All tagged elements with their MCIDs
2. Cross-page element continuations
3. Element boundaries

Optionally extracts MCID bounding boxes from the PDF.

Usage:
    python3 parse_lpsb_mcid.py test.aux test.pdf -o output.json
"""

import re
import sys
import json
import argparse
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple

try:
    import fitz  # PyMuPDF
    HAS_PYMUPDF = True
except ImportError:
    HAS_PYMUPDF = False

try:
    import pdfplumber
    HAS_PDFPLUMBER = True
except ImportError:
    HAS_PDFPLUMBER = False


@dataclass
class MCIDEntry:
    """A single MCID instance on a specific page."""
    mcid: int
    page: int


@dataclass  
class TaggedElement:
    """A logical tagged element (may span multiple pages/MCIDs)."""
    elem_id: int
    tag_type: str
    mcids: List[MCIDEntry] = field(default_factory=list)
    start_page: int = 0
    end_page: int = 0
    is_atom: bool = False  # True for inline elements (Em, Strong, etc.)
    parent_id: Optional[int] = None  # Parent element ID for nested atoms
    ref_key: Optional[str] = None  # Citation key string for Reference atoms
    bbox: Optional[Dict] = None  # {page: [x0, y0, x1, y1]}


def parse_aux_file(aux_path: Path) -> Tuple[List[TaggedElement], Dict]:
    """Parse aux file for MCID structure data.
    
    Returns:
        Tuple of (list of TaggedElements, summary dict)
    """
    elements: Dict[int, TaggedElement] = {}
    summary = {
        "total_elements": 0,
        "total_mcids": 0,
        "total_pages": 0,
    }
    
    content = aux_path.read_text(errors="ignore")
    
    # Pattern: \lpsb@tag@data{elem_id}{type}{mcid}{page}
    tag_data_pattern = re.compile(
        r"\\lpsb@tag@data\{(\d+)\}\{([^}]+)\}\{(\d+)\}\{(\d+)\}"
    )
    
    # Pattern: \lpsb@tag@atom{elem_id}{type}{mcid}{page}{parent_id}
    # Parent ID is optional for backward compatibility
    tag_atom_pattern = re.compile(
        r"\\lpsb@tag@atom\{(\d+)\}\{([^}]+)\}\{(\d+)\}\{(\d+)\}(?:\{(\d+)\})?"
    )
    
    # Pattern: \lpsb@tag@end{elem_id}{page}
    tag_end_pattern = re.compile(
        r"\\lpsb@tag@end\{(\d+)\}\{(\d+)\}"
    )
    
    # Pattern: \lpsb@mcid@cont{elem_id}{mcid}{page}
    mcid_cont_pattern = re.compile(
        r"\\lpsb@mcid@cont\{(\d+)\}\{(\d+)\}\{(\d+)\}"
    )
    
    # Pattern: \lpsb@summary{total_elem}{total_mcid}{total_pages}
    summary_pattern = re.compile(
        r"\\lpsb@summary\{(\d+)\}\{(\d+)\}\{(\d+)\}"
    )

    # Pattern: \lpsb@refkey{elem_id}{cite_keys}
    refkey_pattern = re.compile(
        r"\\lpsb@refkey\{(\d+)\}\{([^}]*)\}"
    )
    
    # Parse tag starts (block elements)
    for m in tag_data_pattern.finditer(content):
        elem_id = int(m.group(1))
        tag_type = m.group(2)
        mcid = int(m.group(3))
        page = int(m.group(4))
        
        elem = TaggedElement(
            elem_id=elem_id,
            tag_type=tag_type,
            start_page=page,
            is_atom=False
        )
        elem.mcids.append(MCIDEntry(mcid=mcid, page=page))
        elements[elem_id] = elem
    
    # Parse atom tags (inline elements, may have parent)
    for m in tag_atom_pattern.finditer(content):
        elem_id = int(m.group(1))
        tag_type = m.group(2)
        mcid = int(m.group(3))
        page = int(m.group(4))
        parent_id = int(m.group(5)) if m.group(5) else None
        
        elem = TaggedElement(
            elem_id=elem_id,
            tag_type=tag_type,
            start_page=page,
            end_page=page,
            is_atom=True,
            parent_id=parent_id
        )
        elem.mcids.append(MCIDEntry(mcid=mcid, page=page))
        elements[elem_id] = elem

    # Parse citation keys (optional metadata for Reference atoms)
    for m in refkey_pattern.finditer(content):
        elem_id = int(m.group(1))
        keys = m.group(2)
        if elem_id in elements:
            elements[elem_id].ref_key = keys
    
    # Parse continuation MCIDs (cross-page)
    for m in mcid_cont_pattern.finditer(content):
        elem_id = int(m.group(1))
        mcid = int(m.group(2))
        page = int(m.group(3))
        
        if elem_id in elements:
            elements[elem_id].mcids.append(MCIDEntry(mcid=mcid, page=page))
    
    # Parse tag ends
    for m in tag_end_pattern.finditer(content):
        elem_id = int(m.group(1))
        page = int(m.group(2))
        
        if elem_id in elements:
            elements[elem_id].end_page = page
    
    # Parse summary
    for m in summary_pattern.finditer(content):
        summary["total_elements"] = int(m.group(1))
        summary["total_mcids"] = int(m.group(2))
        summary["total_pages"] = int(m.group(3))
    
    return list(elements.values()), summary


def extract_mcid_bboxes(pdf_path: Path) -> Dict[int, Dict[int, List[float]]]:
    """Extract bounding boxes for each MCID from PDF using pdfplumber.
    
    pdfplumber exposes 'mcid' attribute on each char object, allowing
    direct mapping of MCID to character bboxes.
    
    Returns:
        Dict of {mcid: {page: [x0, y0, x1, y1]}}
    """
    if not HAS_PDFPLUMBER:
        print("Warning: pdfplumber not available for MCID extraction", file=sys.stderr)
        return {}
    
    bboxes = {}
    
    try:
        pdf = pdfplumber.open(pdf_path)
        
        for page_num, page in enumerate(pdf.pages, 1):
            # Group chars by mcid
            mcid_chars = {}
            
            for char in page.chars:
                mcid = char.get("mcid")
                if mcid is not None:
                    if mcid not in mcid_chars:
                        mcid_chars[mcid] = []
                    mcid_chars[mcid].append(char)
            
            # Calculate bbox for each mcid
            for mcid, chars in mcid_chars.items():
                if chars:
                    x0 = min(c["x0"] for c in chars)
                    y0 = min(c["top"] for c in chars)
                    x1 = max(c["x1"] for c in chars)
                    y1 = max(c["bottom"] for c in chars)
                    
                    if mcid not in bboxes:
                        bboxes[mcid] = {}
                    bboxes[mcid][page_num] = [x0, y0, x1, y1]
        
        pdf.close()
    except Exception as e:
        print(f"Warning: PDF parsing failed: {e}", file=sys.stderr)
    
    return bboxes



def elements_to_json(elements: List[TaggedElement], summary: Dict) -> dict:
    """Convert parsed elements to JSON structure."""
    return {
        "summary": summary,
        "elements": [
            {
                "id": e.elem_id,
                "type": e.tag_type,
                "start_page": e.start_page,
                "end_page": e.end_page,
                "is_atom": e.is_atom,
                "parent_id": e.parent_id,
                "ref_key": e.ref_key,
                "mcids": [
                    {"mcid": m.mcid, "page": m.page}
                    for m in e.mcids
                ],
                "cross_page": len(set(m.page for m in e.mcids)) > 1
            }
            for e in sorted(elements, key=lambda x: x.elem_id)
        ]
    }


def main():
    parser = argparse.ArgumentParser(
        description="Parse LPSB MCID data from aux file"
    )
    parser.add_argument("aux", help="Path to .aux file")
    parser.add_argument("pdf", nargs="?", help="Optional: Path to PDF for bbox extraction")
    parser.add_argument("-o", "--output", help="Output JSON path")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    
    args = parser.parse_args()
    
    aux_path = Path(args.aux)
    if not aux_path.exists():
        print(f"Error: File not found: {aux_path}", file=sys.stderr)
        sys.exit(1)
    
    # Parse aux file
    elements, summary = parse_aux_file(aux_path)
    
    if args.verbose:
        print("=" * 60)
        print("LPSB MCID Structure Data")
        print("=" * 60)
        print(f"\nSummary:")
        print(f"  Total elements: {summary['total_elements']}")
        print(f"  Total MCIDs: {summary['total_mcids']}")
        print(f"  Total pages: {summary['total_pages']}")
        print(f"\nParsed Elements ({len(elements)}):")
        print("-" * 60)
        
        for elem in sorted(elements, key=lambda x: x.elem_id):
            cross = "CROSS-PAGE" if len(set(m.page for m in elem.mcids)) > 1 else ""
            atom = "(atom)" if elem.is_atom else ""
            print(f"\n  [{elem.elem_id}] <{elem.tag_type}> {atom} {cross}")
            print(f"      Pages: {elem.start_page} to {elem.end_page}")
            print(f"      MCIDs: {[m.mcid for m in elem.mcids]}")
    
    # Extract bboxes from PDF if provided
    if args.pdf:
        pdf_path = Path(args.pdf)
        if pdf_path.exists():
            bboxes = extract_mcid_bboxes(pdf_path)
            if args.verbose and bboxes:
                print(f"\nExtracted {len(bboxes)} MCID bboxes from PDF")
    
    # Generate output JSON
    output_data = elements_to_json(elements, summary)
    
    # Write output
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = aux_path.with_suffix(".mcid.json")
    
    with open(output_path, "w") as f:
        json.dump(output_data, f, indent=2)
    
    print(f"✓ Output written to: {output_path}")
    print(f"  Elements: {len(elements)}, MCIDs: {summary['total_mcids']}")


if __name__ == "__main__":
    main()
