#!/bin/bash
# Test script for LuaLaTeX Math Extraction

echo "=== Testing LuaLaTeX Math Support ==="

CONTAINER_IMAGE="lpsb-texlive:latest"
if ! docker image inspect "$CONTAINER_IMAGE" >/dev/null 2>&1; then
    CONTAINER_IMAGE="texlive/texlive:latest"
fi

# Create a test tex file with $...$ math
cat <<EOF > test_math.tex
\documentclass{article}
\usepackage{lpsb}
\usepackage{lpsb-luamath}

\begin{document}
Statement 1: Let \( a = b \).
Statement 2: Consider $E = mc^2$.
Statement 3: 
\[
    \int_0^\infty e^{-x} dx = 1
\]
\end{document}
EOF

# Run compilation
# We map current dir to /workdir
docker run --rm -v "$(pwd)":/workdir -w /workdir $CONTAINER_IMAGE \
    lualatex --interaction=nonstopmode test_math.tex

# Check validation
echo
echo "=== Checking JSON Output ==="
if [ -f "test_math.lpsb.json" ]; then
    # Look for the Math events generated by Lua
    grep "role.*Math" test_math.lpsb.json
else
    echo "ERROR: JSON file not generated"
fi
